Adjusted code to build in VS 2015
* `MetaString::encrypt` and `decrypt` are now both explicitly `const`.
  (`constexpr` doesn't imply `const` in C++14; warning C4814)
* Simplified `RandomSeed` to no longer define `time` or `seed`
  (No declarations inside `constexpr` allowed, error C3250)